config/routes.rb
Practiced::Application.routes.draw do
  
  resources :users

  
  root :to => "pages#home"

  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  
  match '/signup', :to => 'users#new'
  
  

 

end

app/models/user.rb
require 'digest'

class User < ActiveRecord::Base
  attr_accessor :password
  attr_accessible :name, :email, :password, :password_confirmation

  email_regex                    = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name,  :presence    => true,
  :length                        => { :maximum => 50 }

  validates :email, :presence    => true,
  :format                        => { :with => email_regex },
  :uniqueness                    => { :case_sensitive => false }

  validates :password, :presence => true,
  :confirmation                  => true,
  :length                        => { :within => 5..20 }

  before_save :encrypt_password

  #return true if the users password matches the submitted password
  def has_password?(submitted_password)
    #compares encrypted_password with the encrypted version of submitted_password
    encrypted_password == encrypt(submitted_password)
  end

  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil if user.nil?
    return user if user.has_password?(submitted_password)
  end

  private

  def encrypt_password
    self.salt = make_salt unless has_password?(password)
    self.encrypted_password = encrypt(password)
  end

  def encrypt (string)
    secure_hash("#{salt}--#{string}")
  end

  def make_salt
    secure_hash("#{Time.now.utc}--#{password}")
  end

  def secure_hash(string)
    Digest::SHA2.hexdigest(string)
  end

end

# == Schema Information
#
# Table name: users
#
#  id                 :integer         not null, primary key
#  name               :string(255)
#  email              :string(255)
#  created_at         :datetime
#  updated_at         :datetime
#  encrypted_password :string(255)
#  salt               :string(255)
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
  end

  def contact
     @title = "Contact"
  end
  
  def about
     @title = "About"
  end
  
  def help
    @title = "Help"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 
 
 def index
   @users = User.all
 end
 
 
  def new
    @title = "Sign up"
    @user = User.new
  end
  
  def show
    @user = User.find(params[:id])
    @title = @user.name
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:success] = "Welcome to Practiced!"
      redirect_to @user
    else
      flash[:failure] = "There seems to have been a hiccup!"
          @title = "Sign up"
      render 'new'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def title
    base_title = "Practiced"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
  
  def logo
    logo = image_tag("logo.png", :alt => "Practiced", :class => "round")
  end
  
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  
  
  def gravatar_for (user, options = { :size => 50 })
    gravatar_image_tag(user.email.downcase, :alt => h(user.name), 
                                            :class => "gravatar",
                                            :gravatar => options)
  end
end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
			<li><%= link_to "Help", help_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>

	<%= link_to logo, root_path %>
	<nav>
		<ul>
			<li><%= link_to "Home", root_path %></li>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Sign in", "#" %></li>
		</ul>
	</nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title><%= title %></title>
<%= csrf_meta_tag %>
<%= render 'layouts/stylesheets' %>
</head>

<body>
<%= render 'layouts/header' %>

	<div class="container">
	
	<% flash.each do |key,value| %>
	  <div class="alert alert-<%= key %>"><%= value %></div>
	<% end %>
	  
		<section>
			<%= yield %>
		</section>
		<%= render 'layouts/footer' %>
		
		
		<% if Rails.env.development? %>
		<div style="color: white">
		<%= debug(params) %>
		</div>
		<% end %>
		
		
		
		
		</div>
	</body>
</html>

app/views/pages/about.html.erb
<h1>About Practiced</h1>
<p>Some lovely bits and bobs about practiced</p>
<p>Mmmm</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/help.html.erb
HELP!

app/views/pages/home.html.erb
<h1>Practiced</h1>
<p>
Track how often and how much you practice your favourite things
</p>

<%= link_to "sign up now!", signup_path, :class => "signup_button" %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_for(@user) do |f| %>
<%= render 'shared/error_messages' %>

<div class="field">
<%= f.label :name %><br />
<%= f.text_field :name %>
</div>

<div class="field">
<%= f.label :email %><br />
<%= f.text_field :email %>
</div>

<div class="field">
<%= f.label :password %><br />
<%= f.text_field :password %>
</div>

<div class="field">
<%= f.label :password_confirmation %><br />
<%= f.text_field :password_confirmation %>
</div>

<div class="actions">
<%= f.submit "Signup" %>
</div>

<%end %>

app/views/users/show.html.erb
<h1><%= gravatar_for @user %> <%= link_to @user.name, user_path(@user) %></h1>
<h2><%= @user.email %></h2>